### Gets all restaurants
GET http://localhost:8000/restaurants

### Get single restaurant by id
GET http://localhost:8000/restaurants/1

### Create a new Restaurant
POST  http://localhost:8000/restaurants
content-type: application/json

{
  "name": "Burger King XXL",
  "lan": 9.784585,
  "lat": 7.84658,
  "tags": [ 5, 8 ],
  "city": 6,
  "description": "This is a default Burger King",
  "picture": "https://qph.fs.quoracdn.net/main-qimg-730b69c7ec4dabdfc4cd3aac023154ca"
}
