### Gets all users
GET http://localhost:8000/users

### Create new User
POST http://localhost:8000/users
content-type: application/json
{
    "name": "Ben"
}

### Delete User
DELETE http://localhost:8000/users/60efdd441d92df504d24172a

### Update User
PUT http://localhost:8000/users/60efdaa024031c4b60ed7ef3
content-type: application/json
{
    "name": "Franz"
}